### PR TITLE
auth: fixed user identity leak

### LINKED ISSUE #37: User identity leak in the JWT token
In the current implementation, the JWT token contains the zprn of the student. Anyone who has the access to the JWT token, can decode the identity of the user using the zprn. 

Hence, I suggest that we store the `_id` of the mongodb document for the same user in the JWT token. This way out would be made sure that no-one can identify the user.

### PR DESCRIPTION
**Pull request by FaiyazMujawar**
Fixes #37 

In this PR,
- Fixed user identity leak in JWT token.
- Replaced all references in IssueService.js & UserController.js to user `document._id` of the user instead.
- Changed incorrect error code (401: unauthorized) for BAD_REQUEST returned from AuthController.js to correct one (400: BAD_REQUEST).
- Added a function `getUserById()` to get user by document's _id.
- Renamed `getUser()` to `getUserByZprn()` to distinguish from `getUserById()`.

**PS**: I'm not changing loginController in AuthController.js as it deals with login from user & user knows only the zprn, not the document _id.

### CODE REVIEW

**Comment by drigio** [comment]
This looks good. However we are passing `zprn` at various other locations as well. For eg in `userContoller's`  methods., we are passing `zprn` there as well. Please refactor at all the locations otherwise there might be inconsistency and the whole system might crash. Also update the test cases as well.

Edit: There is inconsistency at other controllers as well. You might want to check that out. I dont understand how your code run with these inconsistencies!?

**Comment by FaiyazMujawar** [comment]
> This looks good. However we are passing `zprn` at various other locations as well. For eg in `userContoller's`  methods., we are passing `zprn` there as well. Please refactor at all the locations otherwise there might be inconsistency and the whole system might crash. Also update the test cases as well.
> 
> Edit: There is inconsistency at other controllers as well. You might want to check that out. I dont understand how your code run with these inconsistencies!?

It runs perfectly. In other controllers, say user controller. We need zprn. There, we zprn is used to store a user into database, which is not an issue. Moreover, no zprn is returned from user controller to the client, except for authorities. Also, identity leak is a threat when identity is linked to any issue, the main focus of our application. User controller shows no links to any issue with any user. So I think leaving zprn there is fine. If you think I'm making any mistake, can you please point it out to me??

**Comment by drigio** [comment]
I think we should update everything from `zprn` to `id` because we are told to make a generic system rather than a college based system. So i think we should refactor all the `zprn` to `id`.

**Comment by FaiyazMujawar** [comment]
Okay. I'll look what I can do.

**Review by drigio — APPROVED** [review]
LGTM! Does everything workout properly?

**Comment by FaiyazMujawar** [comment]
Yes. You can go ahead and merge it.

**Pull request merged**
