### PR TITLE
test: Setup testing framework and create test scripts.

### LINKED ISSUE #5: Setup a new testing framework for testing the api endpoints
We should have a way to test the api endpoints that are being added to our repo. Manual testing with Postman is okay for small amount of endpoints and for a short period of time. I think testing it manually will be a tedious task and if any endpoint is migrated into the codebase without proper testing it might be disastrous to change many parts of the code.

We should decide on the libraries that we will be using in our api. Currently what I think is [Mocha](https://mochajs.org/) and [Chai](https://www.chaijs.com/) or [Jest](https://jestjs.io/) and [SuperTest](https://github.com/visionmedia/supertest#readme). Which pair to go with will depend on factors like which is easy to use and simple to write without much boilerplate, and also which one will be helpful for our project in the long run.

Here are some guides to get us started :
Mocha and Chai :- https://scotch.io/tutorials/test-a-node-restful-api-with-mocha-and-chai
Jest and SuperTest :- https://dev.to/nedsoft/testing-nodejs-express-api-with-jest-and-supertest-1km6

### PR DESCRIPTION
**Pull request by drigio**
Fixes #5 

The testing framework that has been chosen is a combination of
1. `Mocha`- as test runner
2. `Chai` - as preferred BDD assertion library
3. `Sinon` - for stubs and mocks
4. `Instanbul` - for code coverage

To create isolated environments, `tools/run-test` script has been created, 
which also simplifies our task of running tests. We need to pass the OPTION
(unit / integration / coverage). 

The `README.md` has been updated with the steps to run the tests.

### CODE REVIEW

**Comment by drigio** [comment]
I'll be adding few tests to this PR as a separate commit. This PR will be considered a `WIP` till then.

**Comment by drigio** [comment]
I have added the unit tests for `UserService.js` file. Will be adding unit tests for others files as well. Will cover the Integration tests in another PR.

**Review by FaiyazMujawar — APPROVED** [review]
I'll need to look into "stubs", as I'm not familiar with the concept. Otherwise, everything looks good. I see you changed a few property names, looks good.

**Comment by drigio** [comment]
@FaiyazMujawar Keywords you can look into - `stubs`, `spies`, `fakes`, `mocks`, `test dummy`, etc. These are majorly used for unit testing. While searching for articles you may find that testing is synonymous with integration testing, but a few articles call it unit testing. These are not the same. Unit tests do not depend on external dependencies and they do not require `api server` running or a database connection. They just check for one single function and their functionality. You'll get a clearer idea when you see our tests and when you find a similar article or video of testing online.

A good playlist but not completely dependable is :- https://www.youtube.com/playlist?list=PLZEZPz6HkCZk30XEdl0eGNhwvoR-XoWHS 
I've sent a few articles on discord's `testing` channel as well. But I would recommend checking for yourself if it's unit testing or integration testing of `rest-api`.

**Comment by drigio** [comment]
I have added necessary unit tests for Services. Will be adding integration tests for routes in a separate PR. Closing and rebasing it. Any changes needed @FaiyazMujawar ?

**Comment by FaiyazMujawar** [comment]
> I have added necessary unit tests for Services. Will be adding integration tests for routes in a separate PR. Closing and rebasing it. Any changes needed @FaiyazMujawar ?

If you think you have done the sufficient, please go ahead and merge the PR. I still do not not have enough grasp on the concept to comment right now. Sorry!

**Comment by drigio** [comment]
@FaiyazMujawar Start reading articles on unit testing and check my previous comments for keywords. Test driven dev is important.

**Comment by FaiyazMujawar** [comment]
Yes @drigio ! Will surely look into the thing!

**Pull request merged**
